### PR TITLE
Core and plugin updates

### PR DESCRIPTION
**Pull request by matt-bernhardt**
This makes a few changes to the application:
- Updates PHP from 7.2 to 7.3
- Updates WordPress core to 5.3.2
- Adds two plugins: WP-CFM (config management) and WP-Mail-SMTP (Email integration)
- Adds app configuration via WP-CFM and the Terminus Secrets infrastructure.

**To review**
Most of this should be visible from within the WP dashboard. In order to verify the email working, go through the lost password process at path `/wp/wp-login.php?action=lostpassword` from the review app.

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/MITLibraries/mitlib-wp-demo/98/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by matt-bernhardt** [comment]
I'm not sure if we want to require one or two approvals on a PR like this, so I'm open to thoughts @JPrevost and @jazairi .

It may also be the case that we need to talk about secrets management on Pantheon before this merges, as part of making this work is to add a password to the secrets setup via Terminus.

**Comment by jazairi** [comment]
@matt-bernhardt Confirmed that the mailer works in the review app. Anything else I should check?

**Comment by matt-bernhardt** [comment]
I've confirmed that the various updates (PHP, WP core) have been applied on the branch, and the two plugins are working and configured (as indicated by the email working, and Pantheon pushing commits back from the review app).

Given this, if nothing you're seeing in the PR raises any flags for you, I think that's sufficient? We haven't talked about the secrets infrastructure, but if you want to see the documentation for that part of the CLI, look at https://github.com/pantheon-systems/terminus-secrets-plugin

**Pull request merged**
